build-and-test:
  tags:
    - lxd
  parallel:
    matrix:
      - DISTRIBUTION: [alpine/edge, debian/9, debian/10]
        ARCH: [amd64, i386]
        BUILD_TYPE: [Debug, Release]
        COMPILER: [gcc, clang]
      - DISTRIBUTION: [centos/7, centos/8]
        ARCH: [amd64]
        BUILD_TYPE: [Debug, Release]
        COMPILER: [gcc, clang]
  image: datamove/$DISTRIBUTION/$ARCH
  script:
    - echo "$DISTRIBUTION", "$ARCH", "$BUILD_TYPE", "$COMPILER"
    - fgrep PRETTY_NAME /etc/os-release
    - uname -m
    - export CFLAGS='-Werror'
    - export CXXFLAGS='-Werror'
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - if [ "$COMPILER" = clang ]; then export CC=clang; fi
    - if [ "$COMPILER" = clang ]; then export CXX=clang++; fi
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE="$BUILD_TYPE"


ubuntu/18.04:
  image: datamove/ubuntu/18.04
  tags:
    - docker
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE=RelWithDebInfo


ubuntu/20.04:
  image: datamove/ubuntu/20.04
  tags:
    - docker
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - export CC=clang
    - export CXX=clang++
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE=Debug
