build-and-test:
  tags:
    - lxd
  parallel:
    matrix:
      - DISTRIBUTION: [alpine/edge, debian/9, debian/10]
        ARCH: [amd64, i386]
        COMPILER: [gcc, clang]
        BUILD_TYPE: [Debug, Release]
      - DISTRIBUTION: [centos/7]
        ARCH: [amd64]
        COMPILER: [gcc, clang]
        BUILD_TYPE: [Debug, Release]
  image: datamove/$DISTRIBUTION/$ARCH
  script:
    - echo "$DISTRIBUTION", "$ARCH", "$COMPILER", "$BUILD_TYPE"
    - fgrep PRETTY_NAME /etc/os-release
    - uname -m
    - export CFLAGS='-Werror'
    - export CXXFLAGS='-Werror'
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - if [ "$COMPILER" = clang ]; then export CC=clang; fi
    - if [ "$COMPILER" = clang ]; then export CXX=clang++; fi
    - mkdir build
    - cd build
    - build_args=''
    - if [ "$DISTRIBUTION" = centos/7 ]; then build_args='-DINSTALL_ZMQ=ON'; fi
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE="$BUILD_TYPE" $build_args
  rules:
    - changes:
      - "*.md"
      when: never
    - when: on_success
