gitlab_runner_latest:
  image: datamove/gitlab-runner/latest
  tags:
    - docker
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - mkdir build
    - cd build
    - bash ../build-and-test.sh ..


gitlab_runner_alpine:
  image: datamove/gitlab-runner/alpine
  tags:
    - docker
  script:
    - export CFLAGS='-march=native'
    - export CXXFLAGS='-march=native'
    - export FCFLAGS='-march=native'
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. Release
