ubuntu/20.04:
  image: datamove/ubuntu/20.04
  tags:
    - docker
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - export CC=clang
    - export CXX=clang++
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE=Debug


centos_8:
  image: datamove/centos/8
  tags:
    - docker
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE=Debug


debian/9/i386:
  image: datamove/debian/9/i386
  tags:
    - lxd
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - export CFLAGS='-march=native'
    - export CXXFLAGS='-march=native'
    - mkdir build
    - cd build
    - bash ../build-and-test.sh .. -DCMAKE_BUILD_TYPE=Release
