gitlab_runner_latest:
  image: datamove/gitlab-runner/latest
  tags:
    - docker
  script:
    - export MALLOC_CHECK_=3
    - export MALLOC_PERTURB_=1
    - mkdir build
    - cd build
    - bash ../build-and-test.sh ..
