# For Melissa 
#RUN echo "Melissa Deps"
#RUN apt-get update
#RUN apt-get install -y pkg-config
#RUN apt-get install -y gfortran libopenmpi-dev openmpi-bin
#RUN apt-get install -y cmake cmake-curses-gui
#RUN apt-get install -y python3
#RUN python3 -m pip install numpy


# SLURM
RUN echo "Slurm"
RUN apt-get update
RUN apt-get install -y slurm-wlm
RUN apt-get install -y mailutils
COPY config/slurm.conf /etc/slurm-llnl/slurm.conf
RUN systemctl enable munge

